import os
import numpy as np
import pytest
import gempy as gp
import gempy_viewer as gpv
import matplotlib.pyplot as plt


def test_enmap_gempy_residual_plots(simple_geo_model, base_dir):
    """
    Test mapping EnMap labels to GemPy labels and plot residuals.
    Mapping: EnMap 0 -> GemPy 1, EnMap 2 -> GemPy 2.
    """
    # 1. Load EnMap extracted points and labels
    # Note: base_dir is project root according to conftest.py
    # But in test_enmap_likelihood.py it seems to be used to find central_xyz.npy
    # Let's check where these files actually are. 
    # Usually they are in a specific Data folder or generated by another test.

    xyz_path = os.path.join(base_dir, 'central_xyz.npy')
    labels_path = os.path.join(base_dir, 'central_labels.npy')

    if not os.path.exists(xyz_path) or not os.path.exists(labels_path):
        # Try to find them in the current directory if base_dir doesn't work as expected
        # in some environments
        xyz_path = 'central_xyz.npy'
        labels_path = 'central_labels.npy'
        if not os.path.exists(xyz_path):
            pytest.skip("EnMap extracted data (central_xyz.npy, central_labels.npy) not found.")

    xyz_central = np.load(xyz_path)
    labels_enmap = np.load(labels_path)

    print(f"\nLoaded {len(xyz_central)} points from EnMap extraction.")

    # 2. Set custom grid in GemPy model
    gp.set_custom_grid(simple_geo_model.grid, xyz_central)

    # 3. Compute GemPy model
    gp.compute_model(simple_geo_model)

    # 4. Get GemPy predicted labels at custom grid points
    labels_gempy = simple_geo_model.solutions.raw_arrays.custom.astype(int)

    # 5. Apply mapping as specified by user
    # EnMap 0 maps to GemPy 2
    # EnMap 2 maps to GemPy 1
    mapping = {
            0: 2,
            2: 1
    }

    mapped_enmap_labels = np.zeros_like(labels_enmap)
    for enmap_val, gempy_val in mapping.items():
        mapped_enmap_labels[labels_enmap == enmap_val] = gempy_val

    # 6. Identify residuals
    # Residual here means where the mapped EnMap labels don't match GemPy labels
    residuals = (mapped_enmap_labels != labels_gempy)
    accuracy = 1.0 - (np.sum(residuals) / len(labels_enmap))

    print(f"Mapping used: {mapping}")
    print(f"Accuracy after mapping: {accuracy:.2%}")

    # 7. Plots
    # We assume xyz_central are on a 2D surface (likely topography)
    x = xyz_central[:, 0]
    y = xyz_central[:, 1]

    fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharex=True, sharey=True)

    # Plot EnMap Labels (Mapped)
    sc0 = axes[0].scatter(x, y, c=mapped_enmap_labels, cmap='viridis', s=10)
    axes[0].set_title('EnMap Labels (Mapped to GemPy IDs)')
    plt.colorbar(sc0, ax=axes[0])

    # Plot GemPy Labels
    sc1 = axes[1].scatter(x, y, c=labels_gempy, cmap='viridis', s=10)
    axes[1].set_title('GemPy Predicted Labels')
    plt.colorbar(sc1, ax=axes[1])

    # Plot Residuals
    # Invert the residuals mask to show mismatches prominently or just plot residuals
    sc2 = axes[2].scatter(x, y, c=residuals, cmap='Reds', s=10)
    axes[2].set_title(f'Residuals (Mismatches)\nAccuracy: {accuracy:.2%}')
    plt.colorbar(sc2, ax=axes[2], label='1 = Mismatch')

    for ax in axes:
        ax.set_aspect('equal')
        ax.set_xlabel('X (m)')
    axes[0].set_ylabel('Y (m)')

    plt.tight_layout()
    plt.show()

    # Optional: 3D plot of residuals
    # gpv.plot_3d(simple_geo_model) # This would plot the whole model

    assert len(labels_gempy) == len(labels_enmap)
